Repository teamHousing/Housing_Android, pull requests merged in 2021-01, with the labels that each got.

#6 [REFACTOR] 패키지 이동 및 파일 이름 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskViewModel.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/ContactAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/data/ContactData.kt
  app/src/main/java/com/teamhousing/housing/util/ChangeButtonAttribute.kt
  app/src/main/res/drawable/border_gray_line_1000.xml
  app/src/main/res/drawable/border_gray_line_12.xml
  app/src/main/res/drawable/border_gray_line_16.xml
  app/src/main/res/layout/activity_write_contact.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_memo.xml
  app/src/main/res/layout/fragment_ask_picture.xml
  app/src/main/res/layout/fragment_ask_time.xml
  app/src/main/res/layout/item_contact.xml
Labels: Android✨, 승완🟢

#12 [ASK] Date & Time Picker 구현
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskViewModel.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/ContactAdapter.kt
  app/src/main/java/com/teamhousing/housing/vo/ContactData.kt
  app/src/main/res/layout/dialog_time_picker.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_memo.xml
  app/src/main/res/layout/fragment_ask_time.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/values/picker_style.xml
Labels: enhancement🎢, 승완🟢

#15 [FEAT] 약속 리스트 추가 완료
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskViewModel.kt
  app/src/main/java/com/teamhousing/housing/util/ChangeButtonAttribute.kt
  app/src/main/res/layout/fragment_ask_time.xml
Labels: enhancement🎢, 승완🟢

#17 [REFACTOR] 버튼 이벤트 수정 완료
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/java/com/teamhousing/housing/util/ChangeButtonAttribute.kt
  app/src/main/res/drawable/border_gray_line_1000.xml
  app/src/main/res/drawable/border_gray_line_12.xml
  app/src/main/res/drawable/border_gray_line_16.xml
  app/src/main/res/drawable/selector_ask_image_button.xml
  app/src/main/res/drawable/selector_memo_button.xml
  app/src/main/res/drawable/selector_memo_edit_text.xml
  app/src/main/res/drawable/selector_problem_button.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_memo.xml
  app/src/main/res/layout/fragment_ask_picture.xml
  app/src/main/res/layout/fragment_ask_time.xml
Labels: ui🎨, 승완🟢

#19 [ADD] 뷰 이벤트 처리
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/res/drawable/border_black_title_underline.xml
  app/src/main/res/drawable/border_gray_title_underline.xml
  app/src/main/res/drawable/border_gray_underline.xml
  app/src/main/res/drawable/selector_underline_edit_text.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_time.xml
Labels: ui🎨, 승완🟢

#21 [REFACTOR] 약속 리스트 추가 코드 수정
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
Labels: enhancement🎢, 승완🟢

#25 [FEAT] 사진 불러오기 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/FilesAdapter.kt
  app/src/main/res/drawable-hdpi/btn_delete.png
  app/src/main/res/drawable-mdpi/btn_delete.png
  app/src/main/res/drawable-xhdpi/btn_delete.png
  app/src/main/res/drawable-xxhdpi/btn_delete.png
  app/src/main/res/drawable-xxxhdpi/btn_delete.png
  app/src/main/res/layout/fragment_ask_picture.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/values/style.xml
Labels: enhancement🎢, 승완🟢

#39 [FEAT] 버튼 활성화 - 다음 단계
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskViewModel.kt
  app/src/main/res/drawable/border_gray2_fill_200.xml
  app/src/main/res/drawable/selector_ask_next_button.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_memo.xml
  app/src/main/res/layout/fragment_ask_picture.xml
  app/src/main/res/layout/fragment_ask_time.xml
  app/src/main/res/layout/item_file.xml
Labels: ui🎨, 승완🟢

#43 [MOD] 짜잘한 수정
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskTimeFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/FilesAdapter.kt
  app/src/main/res/drawable/border_gray_line_200.xml
  app/src/main/res/drawable/border_white_fill_shadow_16.xml
  app/src/main/res/drawable/selector_add_button.xml
  app/src/main/res/layout/dialog_time_picker.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_picture.xml
  app/src/main/res/layout/fragment_ask_time.xml
Labels: ui🎨, 승완🟢

#49 [FEAT] STEP4 프래그먼트에서 액티비티로 변경
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskViewModel.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/ContactAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseViewModel.kt
  app/src/main/res/layout/activity_promise.xml
Labels: enhancement🎢, 승완🟢

#61 home detail view
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamhousing/housing/ui/home/detail/HomeDetailActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/detail/HomeDetailInfoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/detail/HomeDetailNoteFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/detail/HomeDetailViewModel.kt
  app/src/main/java/com/teamhousing/housing/ui/home/detail/adapter/InfoCommunicationListAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/detail/adapter/ViewPagerAdapter.kt
  app/src/main/java/com/teamhousing/housing/utill/MeasuredViewPager.kt
  app/src/main/java/com/teamhousing/housing/vo/InfoCommunicationListData.kt
  app/src/main/res/drawable/border_gray2_line_200.xml
  app/src/main/res/drawable/border_main_gray_fill_12.xml
  app/src/main/res/drawable/tab_home_detail_background.xml
  app/src/main/res/drawable/tab_home_detail_indicator.xml
  app/src/main/res/layout/activity_home_detail.xml
  app/src/main/res/layout/fragment_home_detail_info.xml
  app/src/main/res/layout/fragment_home_detail_note.xml
  app/src/main/res/layout/rv_item_home_detail_info.xml
  app/src/main/res/layout/rv_item_home_detail_note.xml
  app/src/main/res/layout/rv_item_home_detail_photo.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: ui🎨, 명희🦕

#67 [FEAT] 갤러리로부터의 사진이 있거나 사진이 없는 경우 서버 전송
  app/build.gradle
  app/src/main/java/com/teamhousing/housing/network/HousingService.kt
  app/src/main/java/com/teamhousing/housing/network/HousingServiceImpl.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskViewModel.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/FilesAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseViewModel.kt
  app/src/main/java/com/teamhousing/housing/vo/PromiseData.kt
  app/src/main/java/com/teamhousing/housing/vo/RequestAskData.kt
  app/src/main/java/com/teamhousing/housing/vo/RequestAskFileData.kt
  app/src/main/java/com/teamhousing/housing/vo/RequestPromiseData.kt
  app/src/main/java/com/teamhousing/housing/vo/ResponseAskData.kt
  app/src/main/java/com/teamhousing/housing/vo/ResponseAskFileData.kt
  app/src/main/java/com/teamhousing/housing/vo/ResponsePromiseData.kt
  app/src/main/res/layout/activity_promise.xml
  app/src/main/res/layout/activity_write_ask.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/item_promise.xml
Labels: enhancement🎢, 승완🟢

#68 [MOD] 안드 화이팅❤
  app/src/main/java/com/teamhousing/housing/network/HousingService.kt
Labels: Android✨, 가은🐶, 명희🦕, 승완🟢, 예인🌊

#69 [FIX] 서버 연결 코드 수정
  app/build.gradle
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
Labels: enhancement🎢, network☁, 승완🟢

#87 [Common] 로고 수정 + 약속 확정 및 수정
  app/src/main/ic_housing-playstore.png
  app/src/main/java/com/teamhousing/housing/network/HousingService.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseAdapter.kt
  app/src/main/res/layout/activity_promise.xml
  app/src/main/res/layout/fragment_ask_content.xml
  app/src/main/res/layout/fragment_ask_memo.xml
  app/src/main/res/layout/fragment_ask_picture.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_housing.png
  app/src/main/res/mipmap-hdpi/ic_housing_foreground.png
  app/src/main/res/mipmap-hdpi/ic_housing_round.png
  app/src/main/res/mipmap-hdpi/ic_logo.png
  app/src/main/res/mipmap-hdpi/ic_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_housing.png
  app/src/main/res/mipmap-mdpi/ic_housing_foreground.png
  app/src/main/res/mipmap-mdpi/ic_housing_round.png
  app/src/main/res/mipmap-mdpi/ic_logo.png
  app/src/main/res/mipmap-mdpi/ic_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_housing.png
  app/src/main/res/mipmap-xhdpi/ic_housing_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_housing_round.png
  app/src/main/res/mipmap-xhdpi/ic_logo.png
  app/src/main/res/mipmap-xhdpi/ic_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_housing.png
  app/src/main/res/mipmap-xxhdpi/ic_housing_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_housing_round.png
  app/src/main/res/mipmap-xxhdpi/ic_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_housing.png
  app/src/main/res/mipmap-xxxhdpi/ic_housing_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_housing_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_round.png
Labels: Android✨, enhancement🎢, network☁, ui🎨, 승완🟢

#90 [MOD] home detail 수정
  app/src/main/res/drawable-hdpi/img_home_blank.png
  app/src/main/res/drawable-hdpi/img_home_main.png
  app/src/main/res/drawable-mdpi/img_home_blank.png
  app/src/main/res/drawable-mdpi/img_home_main.png
  app/src/main/res/drawable-xhdpi/img_home_blank.png
  app/src/main/res/drawable-xhdpi/img_home_main.png
  app/src/main/res/drawable-xxhdpi/img_home_blank.png
  app/src/main/res/drawable-xxhdpi/img_home_main.png
  app/src/main/res/drawable-xxxhdpi/img_home_blank.png
  app/src/main/res/drawable-xxxhdpi/img_home_main.png
  app/src/main/res/layout/fragment_home.xml
Labels: ui🎨, 명희🦕

#95 [FIX] 버그 수정
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/res/layout/activity_promise.xml
  app/src/main/res/layout/fragment_ask_memo.xml
Labels: ui🎨, 승완🟢

#100 README.md 수정 완료
  README.md
Labels: Android✨, docs, 가은🐶, 명희🦕, 승완🟢, 예인🌊

#101 README.md 수정 완료
  README.md
Labels: Android✨, docs, 가은🐶, 명희🦕, 승완🟢, 예인🌊

#102 README.md 수정 완료
  README.md
Labels: Android✨, docs, 가은🐶, 명희🦕, 승완🟢, 예인🌊

#103 [FEAT] 카메라 기능 추가
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskContentFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskPictureFragment.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/PromiseActivity.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/adapter/FilesAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/adapter/PromiseAdapter.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/viewmodel/AskViewModel.kt
  app/src/main/java/com/teamhousing/housing/ui/home/ask/viewmodel/PromiseViewModel.kt
  app/src/main/res/layout/fragment_home_detail_info.xml
Labels: enhancement🎢, 승완🟢

#111 [MOD] 버튼 뷰 수정
  app/src/main/java/com/teamhousing/housing/ui/home/ask/AskMemoFragment.kt
  app/src/main/res/drawable/selector_ask_next_button.xml
  app/src/main/res/layout/fragment_ask_content.xml
Labels: ui🎨, 승완🟢
